version: '3.4'
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
    entrypoint: [
      "sh", "-c", 
      "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
      # "python manage.py startapp parse"
      ]
  